version: "3.8"

services:
  pepi-web:
    build:
      context: ./app_web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MAILTRAP_API_TOKEN=""
      - EMAIL_FROM=""
      - FACEBOOK_APP_ID=""
    restart: unless-stopped
